version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "gatsby"
      - dependency-name: "gatsby-cli"
      - dependency-name: "gatsby-plugin-manifest"
      - dependency-name: "gatsby-plugin-purgecss"
      - dependency-name: "gatsby-plugin-react-helmet"
      - dependency-name: "gatsby-plugin-sharp"
      - dependency-name: "gatsby-plugin-twitter"
      - dependency-name: "gatsby-remark-images"
      - dependency-name: "gatsby-remark-smartypants"
      - dependency-name: "gatsby-source-filesystem"
      - dependency-name: "gatsby-transformer-remark"
      - dependency-name: "gatsby-transformer-sharp"
      - dependency-name: "@mdx-js/mdx"
      - dependency-name: "prism-react-renderer"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
