version: 2

updates:
  - package-ecosystem: yarn
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 20
